services:
  - type: web
    name: meu-laravel
    env: php
    buildCommand: |
      composer install
      php artisan key:generate
      chmod -R 775 storage bootstrap/cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
